language: erlang
otp_release:
  - 17.0
env:
  - CPATH=/usr/lib/llvm-3.0/include LIBRARY_PATH=/usr/lib/llvm-3.0/lib LD_LIBRARY_PATH=/usr/lib/llvm-3.0/lib
before_install:
  - yes | sudo add-apt-repository ppa:xorg-edgers/ppa 
  - sudo apt-get update
  - sudo apt-get install libclang1-3.4 libclang-3.4-dev
  - dialyzer --build_plt --apps erts kernel stdlib compiler
script: "make all"
